spring.application.name=sistema_cloud_native

server.port=8080

# H2 en memoria
spring.datasource.url=jdbc:h2:mem:guiasdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true

# AWS S3
aws.accessKey=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.sessionToken=${AWS_SESSION_TOKEN}
aws.region=${AWS_REGION}
aws.bucketName=${AWS_BUCKET_NAME}

# Azure AD B2C
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://duocazure6.b2clogin.com/tfp/f46d4161-d548-45fa-b47b-4644faa51b29/b2c_1_signupsignin/v2.0/
